# Generated by Django 3.2.15 on 2023-12-25 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(blank=True, max_length=3, verbose_name='House Number')),
                ('electricity_number', models.CharField(blank=True, max_length=10, verbose_name='Electricity Account Number')),
                ('water_number', models.CharField(blank=True, max_length=10, verbose_name='Water Meter Number')),
                ('rent_amount', models.IntegerField(blank=True, verbose_name='Rent Amout')),
                ('is_vacant', models.BooleanField(default=True)),
                ('house_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
            ],
            options={
                'verbose_name_plural': 'House Data',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('house_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house', verbose_name='House Number')),
                ('tenant_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tenant Name')),
            ],
            options={
                'verbose_name_plural': 'Tenant Data',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Plot Number')),
                ('plot_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('plot_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner Name')),
            ],
            options={
                'verbose_name_plural': 'Plot Data',
                'ordering': ['-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Phone Number')),
                ('amount', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Amount')),
                ('mpesa_transaction_id', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Mpesa Transaction ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated')),
                ('tenant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Tenant Name')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='plot_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plot', verbose_name='Plot Number'),
        ),
    ]
