# Generated by Django 3.2.15 on 2023-12-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MpesaTransaction',
        ),
    ]
