# Generated by Django 3.2.15 on 2022-11-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='Plot/Land Owner'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tenant',
            field=models.BooleanField(default=False, verbose_name='Tenant'),
        ),
    ]
