# Generated by Django 3.2.15 on 2022-12-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221122_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=25, unique=True, verbose_name='Username'),
        ),
    ]
