# Generated by Django 3.2.15 on 2022-10-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNo', models.CharField(blank=True, max_length=3, verbose_name='House Number')),
                ('elecNo', models.CharField(blank=True, max_length=10, verbose_name='Electricity Account Number')),
                ('waterNo', models.CharField(blank=True, max_length=10, verbose_name='Water Meter Number')),
                ('rentAmount', models.IntegerField(blank=True, verbose_name='Rent Amout')),
                ('is_vacant', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'House Details',
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_deed_No', models.CharField(blank=True, max_length=10, verbose_name='Title Deed')),
            ],
            options={
                'verbose_name_plural': 'Plot Details',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Tenant Name')),
                ('natid', models.IntegerField(blank=True, verbose_name='National Identity Number')),
                ('phoneno', models.IntegerField(blank=True, verbose_name='Phone Number')),
                ('image', models.ImageField(blank=True, upload_to='img')),
                ('houseNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.house', verbose_name='House Number')),
            ],
            options={
                'verbose_name_plural': 'Tenant Details',
            },
        ),
        migrations.AddField(
            model_name='house',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plot', verbose_name='Title Deed Number'),
        ),
    ]
