# Generated by Django 3.2.15 on 2022-11-21 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_tenant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='user',
        ),
        migrations.AddField(
            model_name='plot',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
