# Generated by Django 3.2.15 on 2022-11-22 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_tenant_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name_plural': 'House Data'},
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name_plural': 'Plot Data'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'verbose_name_plural': 'Tenant Data'},
        ),
        migrations.RemoveField(
            model_name='plot',
            name='user',
        ),
        migrations.AddField(
            model_name='plot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
