# Generated by Django 3.2.15 on 2022-11-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221122_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='phoneno',
        ),
    ]
