# Generated by Django 3.2.15 on 2022-11-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221125_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='house',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AddField(
            model_name='plot',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='plot',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date Updated'),
        ),
    ]
