# Generated by Django 3.2.15 on 2022-11-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221126_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plot',
            old_name='title_deed_No',
            new_name='plot_no',
        ),
    ]
