# Generated by Django 3.2.15 on 2022-12-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tenant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plot', verbose_name='Plot Number'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='plot_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='Plot Number'),
        ),
    ]
